[15-Jul-2021 17:31:18 Europe/Berlin] PHP Warning:  Undefined array key "role" in D:\XAMPP\htdocs\api\Resources\Auth\AuthController.php on line 54
[15-Jul-2021 17:34:01 Europe/Berlin] PHP Warning:  Undefined array key "role" in D:\XAMPP\htdocs\api\Resources\Auth\AuthController.php on line 54
[15-Jul-2021 17:37:12 Europe/Berlin] PHP Warning:  Undefined array key "role" in D:\XAMPP\htdocs\api\Resources\Auth\AuthController.php on line 54
[15-Jul-2021 17:37:25 Europe/Berlin] PHP Warning:  Undefined array key "role" in D:\XAMPP\htdocs\api\Resources\Auth\AuthController.php on line 54
[15-Jul-2021 17:37:53 Europe/Berlin] PHP Warning:  Undefined array key "role" in D:\XAMPP\htdocs\api\Resources\Auth\AuthController.php on line 54
[15-Jul-2021 17:38:47 Europe/Berlin] PHP Warning:  Undefined array key "role" in D:\XAMPP\htdocs\api\Resources\Auth\AuthController.php on line 54
[15-Jul-2021 17:44:21 Europe/Berlin] PHP Warning:  Undefined array key "role" in D:\XAMPP\htdocs\api\Resources\Auth\AuthController.php on line 54
[15-Jul-2021 17:45:03 Europe/Berlin] PHP Warning:  Undefined array key "role" in D:\XAMPP\htdocs\api\Resources\Auth\AuthController.php on line 54
[15-Jul-2021 17:45:22 Europe/Berlin] PHP Warning:  Undefined array key "role" in D:\XAMPP\htdocs\api\Resources\Auth\AuthController.php on line 54
[15-Jul-2021 17:47:39 Europe/Berlin] PHP Warning:  Undefined array key "role" in D:\XAMPP\htdocs\api\Resources\Auth\AuthController.php on line 54
[15-Jul-2021 17:52:28 Europe/Berlin] PHP Warning:  Undefined array key "role" in D:\XAMPP\htdocs\api\Resources\Auth\AuthController.php on line 54
[15-Jul-2021 17:53:58 Europe/Berlin] PHP Warning:  Undefined array key "role" in D:\XAMPP\htdocs\api\Resources\Auth\AuthController.php on line 54
[15-Jul-2021 17:54:27 Europe/Berlin] PHP Warning:  Undefined array key "role" in D:\XAMPP\htdocs\api\Resources\Auth\AuthController.php on line 54
[15-Jul-2021 17:54:39 Europe/Berlin] PHP Warning:  Undefined array key "role" in D:\XAMPP\htdocs\api\Resources\Auth\AuthController.php on line 54
[15-Jul-2021 17:56:36 Europe/Berlin] PHP Warning:  Undefined array key "role" in D:\XAMPP\htdocs\api\Resources\Auth\AuthController.php on line 54
[15-Jul-2021 17:57:19 Europe/Berlin] PHP Warning:  Undefined array key "role" in D:\XAMPP\htdocs\api\Resources\Auth\AuthController.php on line 54
[15-Jul-2021 18:00:09 Europe/Berlin] PHP Warning:  Array to string conversion in D:\XAMPP\htdocs\api\Resources\Auth\AuthController.php on line 54
[15-Jul-2021 18:02:43 Europe/Berlin] PHP Warning:  Undefined array key 0 in D:\XAMPP\htdocs\api\Resources\Auth\AuthController.php on line 54
[15-Jul-2021 18:02:58 Europe/Berlin] PHP Warning:  Undefined array key "email" in D:\XAMPP\htdocs\api\Resources\Auth\AuthController.php on line 54
[15-Jul-2021 22:51:04 Europe/Berlin] PHP Fatal error:  Uncaught PDOException: SQLSTATE[42000]: Syntax error or access violation: 1066 Not unique table/alias: 'order_details' in D:\XAMPP\htdocs\api\vendor\illuminate\database\Connection.php:338
Stack trace:
#0 D:\XAMPP\htdocs\api\vendor\illuminate\database\Connection.php(338): PDO->prepare('select `SUM(ord...')
#1 D:\XAMPP\htdocs\api\vendor\illuminate\database\Connection.php(671): Illuminate\Database\Connection->Illuminate\Database\{closure}('select `SUM(ord...', Array)
#2 D:\XAMPP\htdocs\api\vendor\illuminate\database\Connection.php(638): Illuminate\Database\Connection->runQueryCallback('select `SUM(ord...', Array, Object(Closure))
#3 D:\XAMPP\htdocs\api\vendor\illuminate\database\Connection.php(346): Illuminate\Database\Connection->run('select `SUM(ord...', Array, Object(Closure))
#4 D:\XAMPP\htdocs\api\vendor\illuminate\database\Query\Builder.php(2313): Illuminate\Database\Connection->select('select `SUM(ord...', Array, true)
#5 D:\XAMPP\htdocs\api\vendor\illuminate\database\Query\Builder.php(2301): Illuminate\Database\Query\Builder->runSelect()
#6 D:\XAMPP\htdocs\api\vendor\illuminate\database\Query\Builder.php(2796): Illuminate\Database\Query\Builder->Illuminate\Database\Query\{closure}()
#7 D:\XAMPP\htdocs\api\vendor\illuminate\database\Query\Builder.php(2302): Illuminate\Database\Query\Builder->onceWithColumns(Array, Object(Closure))
#8 D:\XAMPP\htdocs\api\Resources\Order\OrderModel.php(77): Illuminate\Database\Query\Builder->get()
#9 D:\XAMPP\htdocs\api\Resources\Order\OrderController.php(165): Resources\Order\OrderModel->dashboard('1')
#10 [internal function]: Resources\Order\OrderController->dashboard('1')
#11 D:\XAMPP\htdocs\api\Core\Router.php(170): call_user_func_array(Array, Array)
#12 D:\XAMPP\htdocs\api\Core\Application.php(147): Core\Router->resolve()
#13 D:\XAMPP\htdocs\api\index.php(33): Core\Application::run()
#14 {main}

Next Illuminate\Database\QueryException: SQLSTATE[42000]: Syntax error or access violation: 1066 Not unique table/alias: 'order_details' (SQL: select `SUM(order_details`.`total)` as `revenue` from `order_details` inner join `order_details` on `orders`.`id` = `order_details`.`order_id` where `EXTRACT(DAY FROM CURRENT_TIMESTAMP)` = EXTRACT(DAY FROM orders.created_at) and `orders`.`restaurant_id` = 1) in D:\XAMPP\htdocs\api\vendor\illuminate\database\Connection.php:678
Stack trace:
#0 D:\XAMPP\htdocs\api\vendor\illuminate\database\Connection.php(638): Illuminate\Database\Connection->runQueryCallback('select `SUM(ord...', Array, Object(Closure))
#1 D:\XAMPP\htdocs\api\vendor\illuminate\database\Connection.php(346): Illuminate\Database\Connection->run('select `SUM(ord...', Array, Object(Closure))
#2 D:\XAMPP\htdocs\api\vendor\illuminate\database\Query\Builder.php(2313): Illuminate\Database\Connection->select('select `SUM(ord...', Array, true)
#3 D:\XAMPP\htdocs\api\vendor\illuminate\database\Query\Builder.php(2301): Illuminate\Database\Query\Builder->runSelect()
#4 D:\XAMPP\htdocs\api\vendor\illuminate\database\Query\Builder.php(2796): Illuminate\Database\Query\Builder->Illuminate\Database\Query\{closure}()
#5 D:\XAMPP\htdocs\api\vendor\illuminate\database\Query\Builder.php(2302): Illuminate\Database\Query\Builder->onceWithColumns(Array, Object(Closure))
#6 D:\XAMPP\htdocs\api\Resources\Order\OrderModel.php(77): Illuminate\Database\Query\Builder->get()
#7 D:\XAMPP\htdocs\api\Resources\Order\OrderController.php(165): Resources\Order\OrderModel->dashboard('1')
#8 [internal function]: Resources\Order\OrderController->dashboard('1')
#9 D:\XAMPP\htdocs\api\Core\Router.php(170): call_user_func_array(Array, Array)
#10 D:\XAMPP\htdocs\api\Core\Application.php(147): Core\Router->resolve()
#11 D:\XAMPP\htdocs\api\index.php(33): Core\Application::run()
#12 {main}
  thrown in D:\XAMPP\htdocs\api\vendor\illuminate\database\Connection.php on line 678
[15-Jul-2021 22:55:11 Europe/Berlin] PHP Fatal error:  Uncaught PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'SUM(order_details.total)' in 'field list' in D:\XAMPP\htdocs\api\vendor\illuminate\database\Connection.php:338
Stack trace:
#0 D:\XAMPP\htdocs\api\vendor\illuminate\database\Connection.php(338): PDO->prepare('select `SUM(ord...')
#1 D:\XAMPP\htdocs\api\vendor\illuminate\database\Connection.php(671): Illuminate\Database\Connection->Illuminate\Database\{closure}('select `SUM(ord...', Array)
#2 D:\XAMPP\htdocs\api\vendor\illuminate\database\Connection.php(638): Illuminate\Database\Connection->runQueryCallback('select `SUM(ord...', Array, Object(Closure))
#3 D:\XAMPP\htdocs\api\vendor\illuminate\database\Connection.php(346): Illuminate\Database\Connection->run('select `SUM(ord...', Array, Object(Closure))
#4 D:\XAMPP\htdocs\api\vendor\illuminate\database\Query\Builder.php(2313): Illuminate\Database\Connection->select('select `SUM(ord...', Array, true)
#5 D:\XAMPP\htdocs\api\vendor\illuminate\database\Query\Builder.php(2301): Illuminate\Database\Query\Builder->runSelect()
#6 D:\XAMPP\htdocs\api\vendor\illuminate\database\Query\Builder.php(2796): Illuminate\Database\Query\Builder->Illuminate\Database\Query\{closure}()
#7 D:\XAMPP\htdocs\api\vendor\illuminate\database\Query\Builder.php(2302): Illuminate\Database\Query\Builder->onceWithColumns(Array, Object(Closure))
#8 D:\XAMPP\htdocs\api\Resources\Order\OrderModel.php(77): Illuminate\Database\Query\Builder->get()
#9 D:\XAMPP\htdocs\api\Resources\Order\OrderController.php(165): Resources\Order\OrderModel->dashboard('1')
#10 [internal function]: Resources\Order\OrderController->dashboard('1')
#11 D:\XAMPP\htdocs\api\Core\Router.php(170): call_user_func_array(Array, Array)
#12 D:\XAMPP\htdocs\api\Core\Application.php(147): Core\Router->resolve()
#13 D:\XAMPP\htdocs\api\index.php(33): Core\Application::run()
#14 {main}

Next Illuminate\Database\QueryException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'SUM(order_details.total)' in 'field list' (SQL: select `SUM(order_details`.`total)` as `revenue` from `order_details` inner join `orders` on `orders`.`id` = `order_details`.`order_id` where `EXTRACT(DAY FROM CURRENT_TIMESTAMP)` = EXTRACT(DAY FROM orders.created_at) and `orders`.`restaurant_id` = 1) in D:\XAMPP\htdocs\api\vendor\illuminate\database\Connection.php:678
Stack trace:
#0 D:\XAMPP\htdocs\api\vendor\illuminate\database\Connection.php(638): Illuminate\Database\Connection->runQueryCallback('select `SUM(ord...', Array, Object(Closure))
#1 D:\XAMPP\htdocs\api\vendor\illuminate\database\Connection.php(346): Illuminate\Database\Connection->run('select `SUM(ord...', Array, Object(Closure))
#2 D:\XAMPP\htdocs\api\vendor\illuminate\database\Query\Builder.php(2313): Illuminate\Database\Connection->select('select `SUM(ord...', Array, true)
#3 D:\XAMPP\htdocs\api\vendor\illuminate\database\Query\Builder.php(2301): Illuminate\Database\Query\Builder->runSelect()
#4 D:\XAMPP\htdocs\api\vendor\illuminate\database\Query\Builder.php(2796): Illuminate\Database\Query\Builder->Illuminate\Database\Query\{closure}()
#5 D:\XAMPP\htdocs\api\vendor\illuminate\database\Query\Builder.php(2302): Illuminate\Database\Query\Builder->onceWithColumns(Array, Object(Closure))
#6 D:\XAMPP\htdocs\api\Resources\Order\OrderModel.php(77): Illuminate\Database\Query\Builder->get()
#7 D:\XAMPP\htdocs\api\Resources\Order\OrderController.php(165): Resources\Order\OrderModel->dashboard('1')
#8 [internal function]: Resources\Order\OrderController->dashboard('1')
#9 D:\XAMPP\htdocs\api\Core\Router.php(170): call_user_func_array(Array, Array)
#10 D:\XAMPP\htdocs\api\Core\Application.php(147): Core\Router->resolve()
#11 D:\XAMPP\htdocs\api\index.php(33): Core\Application::run()
#12 {main}
  thrown in D:\XAMPP\htdocs\api\vendor\illuminate\database\Connection.php on line 678
[15-Jul-2021 22:58:04 Europe/Berlin] PHP Fatal error:  Uncaught PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'EXTRACT(DAY FROM CURRENT_TIMESTAMP)' in 'where clause' in D:\XAMPP\htdocs\api\vendor\illuminate\database\Connection.php:338
Stack trace:
#0 D:\XAMPP\htdocs\api\vendor\illuminate\database\Connection.php(338): PDO->prepare('select sum(`ord...')
#1 D:\XAMPP\htdocs\api\vendor\illuminate\database\Connection.php(671): Illuminate\Database\Connection->Illuminate\Database\{closure}('select sum(`ord...', Array)
#2 D:\XAMPP\htdocs\api\vendor\illuminate\database\Connection.php(638): Illuminate\Database\Connection->runQueryCallback('select sum(`ord...', Array, Object(Closure))
#3 D:\XAMPP\htdocs\api\vendor\illuminate\database\Connection.php(346): Illuminate\Database\Connection->run('select sum(`ord...', Array, Object(Closure))
#4 D:\XAMPP\htdocs\api\vendor\illuminate\database\Query\Builder.php(2313): Illuminate\Database\Connection->select('select sum(`ord...', Array, true)
#5 D:\XAMPP\htdocs\api\vendor\illuminate\database\Query\Builder.php(2301): Illuminate\Database\Query\Builder->runSelect()
#6 D:\XAMPP\htdocs\api\vendor\illuminate\database\Query\Builder.php(2796): Illuminate\Database\Query\Builder->Illuminate\Database\Query\{closure}()
#7 D:\XAMPP\htdocs\api\vendor\illuminate\database\Query\Builder.php(2302): Illuminate\Database\Query\Builder->onceWithColumns(Array, Object(Closure))
#8 D:\XAMPP\htdocs\api\vendor\illuminate\database\Query\Builder.php(2723): Illuminate\Database\Query\Builder->get(Array)
#9 D:\XAMPP\htdocs\api\vendor\illuminate\database\Query\Builder.php(2684): Illuminate\Database\Query\Builder->aggregate('sum', Array)
#10 D:\XAMPP\htdocs\api\Resources\Order\OrderModel.php(77): Illuminate\Database\Query\Builder->sum('order_details.t...')
#11 D:\XAMPP\htdocs\api\Resources\Order\OrderController.php(165): Resources\Order\OrderModel->dashboard('1')
#12 [internal function]: Resources\Order\OrderController->dashboard('1')
#13 D:\XAMPP\htdocs\api\Core\Router.php(170): call_user_func_array(Array, Array)
#14 D:\XAMPP\htdocs\api\Core\Application.php(147): Core\Router->resolve()
#15 D:\XAMPP\htdocs\api\index.php(33): Core\Application::run()
#16 {main}

Next Illuminate\Database\QueryException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'EXTRACT(DAY FROM CURRENT_TIMESTAMP)' in 'where clause' (SQL: select sum(`order_details`.`total`) as aggregate from `order_details` inner join `orders` on `orders`.`id` = `order_details`.`order_id` where `EXTRACT(DAY FROM CURRENT_TIMESTAMP)` = EXTRACT(DAY FROM orders.created_at) and `orders`.`restaurant_id` = 1) in D:\XAMPP\htdocs\api\vendor\illuminate\database\Connection.php:678
Stack trace:
#0 D:\XAMPP\htdocs\api\vendor\illuminate\database\Connection.php(638): Illuminate\Database\Connection->runQueryCallback('select sum(`ord...', Array, Object(Closure))
#1 D:\XAMPP\htdocs\api\vendor\illuminate\database\Connection.php(346): Illuminate\Database\Connection->run('select sum(`ord...', Array, Object(Closure))
#2 D:\XAMPP\htdocs\api\vendor\illuminate\database\Query\Builder.php(2313): Illuminate\Database\Connection->select('select sum(`ord...', Array, true)
#3 D:\XAMPP\htdocs\api\vendor\illuminate\database\Query\Builder.php(2301): Illuminate\Database\Query\Builder->runSelect()
#4 D:\XAMPP\htdocs\api\vendor\illuminate\database\Query\Builder.php(2796): Illuminate\Database\Query\Builder->Illuminate\Database\Query\{closure}()
#5 D:\XAMPP\htdocs\api\vendor\illuminate\database\Query\Builder.php(2302): Illuminate\Database\Query\Builder->onceWithColumns(Array, Object(Closure))
#6 D:\XAMPP\htdocs\api\vendor\illuminate\database\Query\Builder.php(2723): Illuminate\Database\Query\Builder->get(Array)
#7 D:\XAMPP\htdocs\api\vendor\illuminate\database\Query\Builder.php(2684): Illuminate\Database\Query\Builder->aggregate('sum', Array)
#8 D:\XAMPP\htdocs\api\Resources\Order\OrderModel.php(77): Illuminate\Database\Query\Builder->sum('order_details.t...')
#9 D:\XAMPP\htdocs\api\Resources\Order\OrderController.php(165): Resources\Order\OrderModel->dashboard('1')
#10 [internal function]: Resources\Order\OrderController->dashboard('1')
#11 D:\XAMPP\htdocs\api\Core\Router.php(170): call_user_func_array(Array, Array)
#12 D:\XAMPP\htdocs\api\Core\Application.php(147): Core\Router->resolve()
#13 D:\XAMPP\htdocs\api\index.php(33): Core\Application::run()
#14 {main}
  thrown in D:\XAMPP\htdocs\api\vendor\illuminate\database\Connection.php on line 678
[16-Jul-2021 00:07:54 Europe/Berlin] PHP Fatal error:  Uncaught PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'EXTRACT(DAY FROM CURRENT_TIMESTAMP)' in 'where clause' in D:\XAMPP\htdocs\api\vendor\illuminate\database\Connection.php:338
Stack trace:
#0 D:\XAMPP\htdocs\api\vendor\illuminate\database\Connection.php(338): PDO->prepare('select sum(`ord...')
#1 D:\XAMPP\htdocs\api\vendor\illuminate\database\Connection.php(671): Illuminate\Database\Connection->Illuminate\Database\{closure}('select sum(`ord...', Array)
#2 D:\XAMPP\htdocs\api\vendor\illuminate\database\Connection.php(638): Illuminate\Database\Connection->runQueryCallback('select sum(`ord...', Array, Object(Closure))
#3 D:\XAMPP\htdocs\api\vendor\illuminate\database\Connection.php(346): Illuminate\Database\Connection->run('select sum(`ord...', Array, Object(Closure))
#4 D:\XAMPP\htdocs\api\vendor\illuminate\database\Query\Builder.php(2313): Illuminate\Database\Connection->select('select sum(`ord...', Array, true)
#5 D:\XAMPP\htdocs\api\vendor\illuminate\database\Query\Builder.php(2301): Illuminate\Database\Query\Builder->runSelect()
#6 D:\XAMPP\htdocs\api\vendor\illuminate\database\Query\Builder.php(2796): Illuminate\Database\Query\Builder->Illuminate\Database\Query\{closure}()
#7 D:\XAMPP\htdocs\api\vendor\illuminate\database\Query\Builder.php(2302): Illuminate\Database\Query\Builder->onceWithColumns(Array, Object(Closure))
#8 D:\XAMPP\htdocs\api\vendor\illuminate\database\Query\Builder.php(2723): Illuminate\Database\Query\Builder->get(Array)
#9 D:\XAMPP\htdocs\api\vendor\illuminate\database\Query\Builder.php(2684): Illuminate\Database\Query\Builder->aggregate('sum', Array)
#10 D:\XAMPP\htdocs\api\Resources\Order\OrderModel.php(77): Illuminate\Database\Query\Builder->sum('order_details.t...')
#11 D:\XAMPP\htdocs\api\Resources\Order\OrderController.php(165): Resources\Order\OrderModel->dashboard('1')
#12 [internal function]: Resources\Order\OrderController->dashboard('1')
#13 D:\XAMPP\htdocs\api\Core\Router.php(170): call_user_func_array(Array, Array)
#14 D:\XAMPP\htdocs\api\Core\Application.php(147): Core\Router->resolve()
#15 D:\XAMPP\htdocs\api\index.php(33): Core\Application::run()
#16 {main}

Next Illuminate\Database\QueryException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'EXTRACT(DAY FROM CURRENT_TIMESTAMP)' in 'where clause' (SQL: select sum(`order_details`.`total`) as aggregate from `order_details` inner join `orders` on `orders`.`id` = `order_details`.`order_id` where `EXTRACT(DAY FROM CURRENT_TIMESTAMP)` = EXTRACT(DAY FROM orders.created_at) and `orders`.`restaurant_id` = 1) in D:\XAMPP\htdocs\api\vendor\illuminate\database\Connection.php:678
Stack trace:
#0 D:\XAMPP\htdocs\api\vendor\illuminate\database\Connection.php(638): Illuminate\Database\Connection->runQueryCallback('select sum(`ord...', Array, Object(Closure))
#1 D:\XAMPP\htdocs\api\vendor\illuminate\database\Connection.php(346): Illuminate\Database\Connection->run('select sum(`ord...', Array, Object(Closure))
#2 D:\XAMPP\htdocs\api\vendor\illuminate\database\Query\Builder.php(2313): Illuminate\Database\Connection->select('select sum(`ord...', Array, true)
#3 D:\XAMPP\htdocs\api\vendor\illuminate\database\Query\Builder.php(2301): Illuminate\Database\Query\Builder->runSelect()
#4 D:\XAMPP\htdocs\api\vendor\illuminate\database\Query\Builder.php(2796): Illuminate\Database\Query\Builder->Illuminate\Database\Query\{closure}()
#5 D:\XAMPP\htdocs\api\vendor\illuminate\database\Query\Builder.php(2302): Illuminate\Database\Query\Builder->onceWithColumns(Array, Object(Closure))
#6 D:\XAMPP\htdocs\api\vendor\illuminate\database\Query\Builder.php(2723): Illuminate\Database\Query\Builder->get(Array)
#7 D:\XAMPP\htdocs\api\vendor\illuminate\database\Query\Builder.php(2684): Illuminate\Database\Query\Builder->aggregate('sum', Array)
#8 D:\XAMPP\htdocs\api\Resources\Order\OrderModel.php(77): Illuminate\Database\Query\Builder->sum('order_details.t...')
#9 D:\XAMPP\htdocs\api\Resources\Order\OrderController.php(165): Resources\Order\OrderModel->dashboard('1')
#10 [internal function]: Resources\Order\OrderController->dashboard('1')
#11 D:\XAMPP\htdocs\api\Core\Router.php(170): call_user_func_array(Array, Array)
#12 D:\XAMPP\htdocs\api\Core\Application.php(147): Core\Router->resolve()
#13 D:\XAMPP\htdocs\api\index.php(33): Core\Application::run()
#14 {main}
  thrown in D:\XAMPP\htdocs\api\vendor\illuminate\database\Connection.php on line 678
[16-Jul-2021 00:10:11 Europe/Berlin] PHP Fatal error:  Uncaught PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'EXTRACT(DAY FROM CURRENT_TIMESTAMP)' in 'where clause' in D:\XAMPP\htdocs\api\vendor\illuminate\database\Connection.php:338
Stack trace:
#0 D:\XAMPP\htdocs\api\vendor\illuminate\database\Connection.php(338): PDO->prepare('select sum(`ord...')
#1 D:\XAMPP\htdocs\api\vendor\illuminate\database\Connection.php(671): Illuminate\Database\Connection->Illuminate\Database\{closure}('select sum(`ord...', Array)
#2 D:\XAMPP\htdocs\api\vendor\illuminate\database\Connection.php(638): Illuminate\Database\Connection->runQueryCallback('select sum(`ord...', Array, Object(Closure))
#3 D:\XAMPP\htdocs\api\vendor\illuminate\database\Connection.php(346): Illuminate\Database\Connection->run('select sum(`ord...', Array, Object(Closure))
#4 D:\XAMPP\htdocs\api\vendor\illuminate\database\Query\Builder.php(2313): Illuminate\Database\Connection->select('select sum(`ord...', Array, true)
#5 D:\XAMPP\htdocs\api\vendor\illuminate\database\Query\Builder.php(2301): Illuminate\Database\Query\Builder->runSelect()
#6 D:\XAMPP\htdocs\api\vendor\illuminate\database\Query\Builder.php(2796): Illuminate\Database\Query\Builder->Illuminate\Database\Query\{closure}()
#7 D:\XAMPP\htdocs\api\vendor\illuminate\database\Query\Builder.php(2302): Illuminate\Database\Query\Builder->onceWithColumns(Array, Object(Closure))
#8 D:\XAMPP\htdocs\api\vendor\illuminate\database\Query\Builder.php(2723): Illuminate\Database\Query\Builder->get(Array)
#9 D:\XAMPP\htdocs\api\vendor\illuminate\database\Query\Builder.php(2684): Illuminate\Database\Query\Builder->aggregate('sum', Array)
#10 D:\XAMPP\htdocs\api\Resources\Order\OrderModel.php(77): Illuminate\Database\Query\Builder->sum('order_details.t...')
#11 D:\XAMPP\htdocs\api\Resources\Order\OrderController.php(165): Resources\Order\OrderModel->dashboard('1')
#12 [internal function]: Resources\Order\OrderController->dashboard('1')
#13 D:\XAMPP\htdocs\api\Core\Router.php(170): call_user_func_array(Array, Array)
#14 D:\XAMPP\htdocs\api\Core\Application.php(147): Core\Router->resolve()
#15 D:\XAMPP\htdocs\api\index.php(33): Core\Application::run()
#16 {main}

Next Illuminate\Database\QueryException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'EXTRACT(DAY FROM CURRENT_TIMESTAMP)' in 'where clause' (SQL: select sum(`order_details`.`total`) as aggregate from `order_details` inner join `orders` on `orders`.`id` = `order_details`.`order_id` where `EXTRACT(DAY FROM CURRENT_TIMESTAMP)` = EXTRACT(DAY FROM orders.created_at) and `orders`.`restaurant_id` = 1) in D:\XAMPP\htdocs\api\vendor\illuminate\database\Connection.php:678
Stack trace:
#0 D:\XAMPP\htdocs\api\vendor\illuminate\database\Connection.php(638): Illuminate\Database\Connection->runQueryCallback('select sum(`ord...', Array, Object(Closure))
#1 D:\XAMPP\htdocs\api\vendor\illuminate\database\Connection.php(346): Illuminate\Database\Connection->run('select sum(`ord...', Array, Object(Closure))
#2 D:\XAMPP\htdocs\api\vendor\illuminate\database\Query\Builder.php(2313): Illuminate\Database\Connection->select('select sum(`ord...', Array, true)
#3 D:\XAMPP\htdocs\api\vendor\illuminate\database\Query\Builder.php(2301): Illuminate\Database\Query\Builder->runSelect()
#4 D:\XAMPP\htdocs\api\vendor\illuminate\database\Query\Builder.php(2796): Illuminate\Database\Query\Builder->Illuminate\Database\Query\{closure}()
#5 D:\XAMPP\htdocs\api\vendor\illuminate\database\Query\Builder.php(2302): Illuminate\Database\Query\Builder->onceWithColumns(Array, Object(Closure))
#6 D:\XAMPP\htdocs\api\vendor\illuminate\database\Query\Builder.php(2723): Illuminate\Database\Query\Builder->get(Array)
#7 D:\XAMPP\htdocs\api\vendor\illuminate\database\Query\Builder.php(2684): Illuminate\Database\Query\Builder->aggregate('sum', Array)
#8 D:\XAMPP\htdocs\api\Resources\Order\OrderModel.php(77): Illuminate\Database\Query\Builder->sum('order_details.t...')
#9 D:\XAMPP\htdocs\api\Resources\Order\OrderController.php(165): Resources\Order\OrderModel->dashboard('1')
#10 [internal function]: Resources\Order\OrderController->dashboard('1')
#11 D:\XAMPP\htdocs\api\Core\Router.php(170): call_user_func_array(Array, Array)
#12 D:\XAMPP\htdocs\api\Core\Application.php(147): Core\Router->resolve()
#13 D:\XAMPP\htdocs\api\index.php(33): Core\Application::run()
#14 {main}
  thrown in D:\XAMPP\htdocs\api\vendor\illuminate\database\Connection.php on line 678
[16-Jul-2021 00:14:27 Europe/Berlin] PHP Fatal error:  Uncaught PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'present' in 'where clause' in D:\XAMPP\htdocs\api\vendor\illuminate\database\Connection.php:338
Stack trace:
#0 D:\XAMPP\htdocs\api\vendor\illuminate\database\Connection.php(338): PDO->prepare('select sum(`ord...')
#1 D:\XAMPP\htdocs\api\vendor\illuminate\database\Connection.php(671): Illuminate\Database\Connection->Illuminate\Database\{closure}('select sum(`ord...', Array)
#2 D:\XAMPP\htdocs\api\vendor\illuminate\database\Connection.php(638): Illuminate\Database\Connection->runQueryCallback('select sum(`ord...', Array, Object(Closure))
#3 D:\XAMPP\htdocs\api\vendor\illuminate\database\Connection.php(346): Illuminate\Database\Connection->run('select sum(`ord...', Array, Object(Closure))
#4 D:\XAMPP\htdocs\api\vendor\illuminate\database\Query\Builder.php(2313): Illuminate\Database\Connection->select('select sum(`ord...', Array, true)
#5 D:\XAMPP\htdocs\api\vendor\illuminate\database\Query\Builder.php(2301): Illuminate\Database\Query\Builder->runSelect()
#6 D:\XAMPP\htdocs\api\vendor\illuminate\database\Query\Builder.php(2796): Illuminate\Database\Query\Builder->Illuminate\Database\Query\{closure}()
#7 D:\XAMPP\htdocs\api\vendor\illuminate\database\Query\Builder.php(2302): Illuminate\Database\Query\Builder->onceWithColumns(Array, Object(Closure))
#8 D:\XAMPP\htdocs\api\vendor\illuminate\database\Query\Builder.php(2723): Illuminate\Database\Query\Builder->get(Array)
#9 D:\XAMPP\htdocs\api\vendor\illuminate\database\Query\Builder.php(2684): Illuminate\Database\Query\Builder->aggregate('sum', Array)
#10 D:\XAMPP\htdocs\api\Resources\Order\OrderModel.php(78): Illuminate\Database\Query\Builder->sum('order_details.t...')
#11 D:\XAMPP\htdocs\api\Resources\Order\OrderController.php(165): Resources\Order\OrderModel->dashboard('1')
#12 [internal function]: Resources\Order\OrderController->dashboard('1')
#13 D:\XAMPP\htdocs\api\Core\Router.php(170): call_user_func_array(Array, Array)
#14 D:\XAMPP\htdocs\api\Core\Application.php(147): Core\Router->resolve()
#15 D:\XAMPP\htdocs\api\index.php(33): Core\Application::run()
#16 {main}

Next Illuminate\Database\QueryException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'present' in 'where clause' (SQL: select sum(`order_details`.`total`) as aggregate from `order_details` inner join `orders` on `orders`.`id` = `order_details`.`order_id` where `present` = orderTime) and `orders`.`restaurant_id` = 1) in D:\XAMPP\htdocs\api\vendor\illuminate\database\Connection.php:678
Stack trace:
#0 D:\XAMPP\htdocs\api\vendor\illuminate\database\Connection.php(638): Illuminate\Database\Connection->runQueryCallback('select sum(`ord...', Array, Object(Closure))
#1 D:\XAMPP\htdocs\api\vendor\illuminate\database\Connection.php(346): Illuminate\Database\Connection->run('select sum(`ord...', Array, Object(Closure))
#2 D:\XAMPP\htdocs\api\vendor\illuminate\database\Query\Builder.php(2313): Illuminate\Database\Connection->select('select sum(`ord...', Array, true)
#3 D:\XAMPP\htdocs\api\vendor\illuminate\database\Query\Builder.php(2301): Illuminate\Database\Query\Builder->runSelect()
#4 D:\XAMPP\htdocs\api\vendor\illuminate\database\Query\Builder.php(2796): Illuminate\Database\Query\Builder->Illuminate\Database\Query\{closure}()
#5 D:\XAMPP\htdocs\api\vendor\illuminate\database\Query\Builder.php(2302): Illuminate\Database\Query\Builder->onceWithColumns(Array, Object(Closure))
#6 D:\XAMPP\htdocs\api\vendor\illuminate\database\Query\Builder.php(2723): Illuminate\Database\Query\Builder->get(Array)
#7 D:\XAMPP\htdocs\api\vendor\illuminate\database\Query\Builder.php(2684): Illuminate\Database\Query\Builder->aggregate('sum', Array)
#8 D:\XAMPP\htdocs\api\Resources\Order\OrderModel.php(78): Illuminate\Database\Query\Builder->sum('order_details.t...')
#9 D:\XAMPP\htdocs\api\Resources\Order\OrderController.php(165): Resources\Order\OrderModel->dashboard('1')
#10 [internal function]: Resources\Order\OrderController->dashboard('1')
#11 D:\XAMPP\htdocs\api\Core\Router.php(170): call_user_func_array(Array, Array)
#12 D:\XAMPP\htdocs\api\Core\Application.php(147): Core\Router->resolve()
#13 D:\XAMPP\htdocs\api\index.php(33): Core\Application::run()
#14 {main}
  thrown in D:\XAMPP\htdocs\api\vendor\illuminate\database\Connection.php on line 678
[16-Jul-2021 15:24:35 Europe/Berlin] PHP Warning:  Array to string conversion in D:\XAMPP\htdocs\api\Resources\Order\OrderModel.php on line 88
[16-Jul-2021 15:24:52 Europe/Berlin] PHP Warning:  Undefined array key "revenue" in D:\XAMPP\htdocs\api\Resources\Order\OrderModel.php on line 88
[16-Jul-2021 15:25:14 Europe/Berlin] PHP Warning:  Undefined array key "revenue" in D:\XAMPP\htdocs\api\Resources\Order\OrderModel.php on line 88
[16-Jul-2021 15:25:14 Europe/Berlin] PHP Warning:  Array to string conversion in D:\XAMPP\htdocs\api\Resources\Order\OrderModel.php on line 88
[16-Jul-2021 15:25:35 Europe/Berlin] PHP Warning:  Undefined array key "data" in D:\XAMPP\htdocs\api\Resources\Order\OrderModel.php on line 88
[16-Jul-2021 15:25:35 Europe/Berlin] PHP Warning:  Trying to access array offset on value of type null in D:\XAMPP\htdocs\api\Resources\Order\OrderModel.php on line 88
[16-Jul-2021 15:25:49 Europe/Berlin] PHP Fatal error:  Uncaught Error: Undefined constant "Resources\Order\data" in D:\XAMPP\htdocs\api\Resources\Order\OrderModel.php:88
Stack trace:
#0 D:\XAMPP\htdocs\api\Resources\Order\OrderController.php(165): Resources\Order\OrderModel->dashboard('1')
#1 [internal function]: Resources\Order\OrderController->dashboard('1')
#2 D:\XAMPP\htdocs\api\Core\Router.php(170): call_user_func_array(Array, Array)
#3 D:\XAMPP\htdocs\api\Core\Application.php(147): Core\Router->resolve()
#4 D:\XAMPP\htdocs\api\index.php(33): Core\Application::run()
#5 {main}
  thrown in D:\XAMPP\htdocs\api\Resources\Order\OrderModel.php on line 88
[16-Jul-2021 15:27:36 Europe/Berlin] PHP Fatal error:  Uncaught TypeError: Cannot access offset of type string on string in D:\XAMPP\htdocs\api\Resources\Order\OrderModel.php:88
Stack trace:
#0 D:\XAMPP\htdocs\api\Resources\Order\OrderController.php(165): Resources\Order\OrderModel->dashboard('1')
#1 [internal function]: Resources\Order\OrderController->dashboard('1')
#2 D:\XAMPP\htdocs\api\Core\Router.php(170): call_user_func_array(Array, Array)
#3 D:\XAMPP\htdocs\api\Core\Application.php(147): Core\Router->resolve()
#4 D:\XAMPP\htdocs\api\index.php(33): Core\Application::run()
#5 {main}
  thrown in D:\XAMPP\htdocs\api\Resources\Order\OrderModel.php on line 88
[16-Jul-2021 15:40:12 Europe/Berlin] PHP Fatal error:  Uncaught Error: Object of class stdClass could not be converted to string in D:\XAMPP\htdocs\api\Resources\Order\OrderModel.php:80
Stack trace:
#0 D:\XAMPP\htdocs\api\Resources\Order\OrderController.php(165): Resources\Order\OrderModel->dashboard('1')
#1 [internal function]: Resources\Order\OrderController->dashboard('1')
#2 D:\XAMPP\htdocs\api\Core\Router.php(170): call_user_func_array(Array, Array)
#3 D:\XAMPP\htdocs\api\Core\Application.php(147): Core\Router->resolve()
#4 D:\XAMPP\htdocs\api\index.php(33): Core\Application::run()
#5 {main}
  thrown in D:\XAMPP\htdocs\api\Resources\Order\OrderModel.php on line 80
[16-Jul-2021 15:40:31 Europe/Berlin] PHP Fatal error:  Uncaught Error: Cannot use object of type stdClass as array in D:\XAMPP\htdocs\api\Resources\Order\OrderModel.php:80
Stack trace:
#0 D:\XAMPP\htdocs\api\Resources\Order\OrderController.php(165): Resources\Order\OrderModel->dashboard('1')
#1 [internal function]: Resources\Order\OrderController->dashboard('1')
#2 D:\XAMPP\htdocs\api\Core\Router.php(170): call_user_func_array(Array, Array)
#3 D:\XAMPP\htdocs\api\Core\Application.php(147): Core\Router->resolve()
#4 D:\XAMPP\htdocs\api\index.php(33): Core\Application::run()
#5 {main}
  thrown in D:\XAMPP\htdocs\api\Resources\Order\OrderModel.php on line 80
[16-Jul-2021 15:41:56 Europe/Berlin] PHP Fatal error:  Uncaught TypeError: json_decode(): Argument #1 ($json) must be of type string, array given in D:\XAMPP\htdocs\api\Resources\Order\OrderModel.php:79
Stack trace:
#0 D:\XAMPP\htdocs\api\Resources\Order\OrderModel.php(79): json_decode(Array, true)
#1 D:\XAMPP\htdocs\api\Resources\Order\OrderController.php(165): Resources\Order\OrderModel->dashboard('1')
#2 [internal function]: Resources\Order\OrderController->dashboard('1')
#3 D:\XAMPP\htdocs\api\Core\Router.php(170): call_user_func_array(Array, Array)
#4 D:\XAMPP\htdocs\api\Core\Application.php(147): Core\Router->resolve()
#5 D:\XAMPP\htdocs\api\index.php(33): Core\Application::run()
#6 {main}
  thrown in D:\XAMPP\htdocs\api\Resources\Order\OrderModel.php on line 79
[16-Jul-2021 15:43:04 Europe/Berlin] PHP Fatal error:  Uncaught Error: Object of class stdClass could not be converted to string in D:\XAMPP\htdocs\api\Resources\Order\OrderModel.php:80
Stack trace:
#0 D:\XAMPP\htdocs\api\Resources\Order\OrderController.php(165): Resources\Order\OrderModel->dashboard('1')
#1 [internal function]: Resources\Order\OrderController->dashboard('1')
#2 D:\XAMPP\htdocs\api\Core\Router.php(170): call_user_func_array(Array, Array)
#3 D:\XAMPP\htdocs\api\Core\Application.php(147): Core\Router->resolve()
#4 D:\XAMPP\htdocs\api\index.php(33): Core\Application::run()
#5 {main}
  thrown in D:\XAMPP\htdocs\api\Resources\Order\OrderModel.php on line 80
[16-Jul-2021 15:43:22 Europe/Berlin] PHP Fatal error:  Uncaught Error: Undefined constant "Resources\Order\data" in D:\XAMPP\htdocs\api\Resources\Order\OrderModel.php:79
Stack trace:
#0 D:\XAMPP\htdocs\api\Resources\Order\OrderController.php(165): Resources\Order\OrderModel->dashboard('1')
#1 [internal function]: Resources\Order\OrderController->dashboard('1')
#2 D:\XAMPP\htdocs\api\Core\Router.php(170): call_user_func_array(Array, Array)
#3 D:\XAMPP\htdocs\api\Core\Application.php(147): Core\Router->resolve()
#4 D:\XAMPP\htdocs\api\index.php(33): Core\Application::run()
#5 {main}
  thrown in D:\XAMPP\htdocs\api\Resources\Order\OrderModel.php on line 79
[16-Jul-2021 15:44:28 Europe/Berlin] PHP Fatal error:  Uncaught Error: Cannot use object of type stdClass as array in D:\XAMPP\htdocs\api\Resources\Order\OrderModel.php:79
Stack trace:
#0 D:\XAMPP\htdocs\api\Resources\Order\OrderController.php(165): Resources\Order\OrderModel->dashboard('1')
#1 [internal function]: Resources\Order\OrderController->dashboard('1')
#2 D:\XAMPP\htdocs\api\Core\Router.php(170): call_user_func_array(Array, Array)
#3 D:\XAMPP\htdocs\api\Core\Application.php(147): Core\Router->resolve()
#4 D:\XAMPP\htdocs\api\index.php(33): Core\Application::run()
#5 {main}
  thrown in D:\XAMPP\htdocs\api\Resources\Order\OrderModel.php on line 79
[16-Jul-2021 15:46:26 Europe/Berlin] PHP Warning:  Array to string conversion in D:\XAMPP\htdocs\api\Resources\Order\OrderModel.php on line 82
[16-Jul-2021 15:48:11 Europe/Berlin] PHP Warning:  Undefined variable $result in D:\XAMPP\htdocs\api\Resources\Order\OrderModel.php on line 80
[16-Jul-2021 17:01:22 Europe/Berlin] PHP Fatal error:  Uncaught PDOException: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'EXTRACT(DAY FROM '2021-04-09 12:45:10') = EXTRACT(DAY FROM orders.created_at)
	' at line 4 in D:\XAMPP\htdocs\api\vendor\illuminate\database\Connection.php:338
Stack trace:
#0 D:\XAMPP\htdocs\api\vendor\illuminate\database\Connection.php(338): PDO->prepare('SELECT date_for...')
#1 D:\XAMPP\htdocs\api\vendor\illuminate\database\Connection.php(671): Illuminate\Database\Connection->Illuminate\Database\{closure}('SELECT date_for...', Array)
#2 D:\XAMPP\htdocs\api\vendor\illuminate\database\Connection.php(638): Illuminate\Database\Connection->runQueryCallback('SELECT date_for...', Array, Object(Closure))
#3 D:\XAMPP\htdocs\api\vendor\illuminate\database\Connection.php(346): Illuminate\Database\Connection->run('SELECT date_for...', Array, Object(Closure))
#4 D:\XAMPP\htdocs\api\vendor\illuminate\database\Capsule\Manager.php(200): Illuminate\Database\Connection->select('SELECT date_for...')
#5 D:\XAMPP\htdocs\api\Resources\Order\OrderModel.php(97): Illuminate\Database\Capsule\Manager::__callStatic('select', Array)
#6 D:\XAMPP\htdocs\api\Resources\Order\OrderController.php(165): Resources\Order\OrderModel->dashboard('1')
#7 [internal function]: Resources\Order\OrderController->dashboard('1')
#8 D:\XAMPP\htdocs\api\Core\Router.php(170): call_user_func_array(Array, Array)
#9 D:\XAMPP\htdocs\api\Core\Application.php(147): Core\Router->resolve()
#10 D:\XAMPP\htdocs\api\index.php(33): Core\Application::run()
#11 {main}

Next Illuminate\Database\QueryException: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'EXTRACT(DAY FROM '2021-04-09 12:45:10') = EXTRACT(DAY FROM orders.created_at)
	' at line 4 (SQL: SELECT date_format(orders.created_at,'%H %p') as hour,
			  count(orders.id) as hourly_orders
		FROM nofipayn_restaurant_reservations_system.orders
		WHERE nofipayn_restaurant_reservations_system.orders.restaurant_id = 1AND EXTRACT(DAY FROM '2021-04-09 12:45:10') = EXTRACT(DAY FROM orders.created_at)
		GROUP BY date_format(orders.created_at,'%H %p')
		order by hourly_orders desc;  ) in D:\XAMPP\htdocs\api\vendor\illuminate\database\Connection.php:678
Stack trace:
#0 D:\XAMPP\htdocs\api\vendor\illuminate\database\Connection.php(638): Illuminate\Database\Connection->runQueryCallback('SELECT date_for...', Array, Object(Closure))
#1 D:\XAMPP\htdocs\api\vendor\illuminate\database\Connection.php(346): Illuminate\Database\Connection->run('SELECT date_for...', Array, Object(Closure))
#2 D:\XAMPP\htdocs\api\vendor\illuminate\database\Capsule\Manager.php(200): Illuminate\Database\Connection->select('SELECT date_for...')
#3 D:\XAMPP\htdocs\api\Resources\Order\OrderModel.php(97): Illuminate\Database\Capsule\Manager::__callStatic('select', Array)
#4 D:\XAMPP\htdocs\api\Resources\Order\OrderController.php(165): Resources\Order\OrderModel->dashboard('1')
#5 [internal function]: Resources\Order\OrderController->dashboard('1')
#6 D:\XAMPP\htdocs\api\Core\Router.php(170): call_user_func_array(Array, Array)
#7 D:\XAMPP\htdocs\api\Core\Application.php(147): Core\Router->resolve()
#8 D:\XAMPP\htdocs\api\index.php(33): Core\Application::run()
#9 {main}
  thrown in D:\XAMPP\htdocs\api\vendor\illuminate\database\Connection.php on line 678
[16-Jul-2021 17:03:03 Europe/Berlin] PHP Fatal error:  Uncaught Error: Cannot use object of type stdClass as array in D:\XAMPP\htdocs\api\Resources\Order\OrderModel.php:98
Stack trace:
#0 D:\XAMPP\htdocs\api\Resources\Order\OrderController.php(165): Resources\Order\OrderModel->dashboard('1')
#1 [internal function]: Resources\Order\OrderController->dashboard('1')
#2 D:\XAMPP\htdocs\api\Core\Router.php(170): call_user_func_array(Array, Array)
#3 D:\XAMPP\htdocs\api\Core\Application.php(147): Core\Router->resolve()
#4 D:\XAMPP\htdocs\api\index.php(33): Core\Application::run()
#5 {main}
  thrown in D:\XAMPP\htdocs\api\Resources\Order\OrderModel.php on line 98
[16-Jul-2021 17:03:15 Europe/Berlin] PHP Fatal error:  Uncaught Error: Object of class stdClass could not be converted to string in D:\XAMPP\htdocs\api\Resources\Order\OrderModel.php:98
Stack trace:
#0 D:\XAMPP\htdocs\api\Resources\Order\OrderController.php(165): Resources\Order\OrderModel->dashboard('1')
#1 [internal function]: Resources\Order\OrderController->dashboard('1')
#2 D:\XAMPP\htdocs\api\Core\Router.php(170): call_user_func_array(Array, Array)
#3 D:\XAMPP\htdocs\api\Core\Application.php(147): Core\Router->resolve()
#4 D:\XAMPP\htdocs\api\index.php(33): Core\Application::run()
#5 {main}
  thrown in D:\XAMPP\htdocs\api\Resources\Order\OrderModel.php on line 98
[16-Jul-2021 17:03:49 Europe/Berlin] PHP Fatal error:  Uncaught Error: Object of class stdClass could not be converted to string in D:\XAMPP\htdocs\api\Resources\Order\OrderModel.php:98
Stack trace:
#0 D:\XAMPP\htdocs\api\Resources\Order\OrderController.php(165): Resources\Order\OrderModel->dashboard('1')
#1 [internal function]: Resources\Order\OrderController->dashboard('1')
#2 D:\XAMPP\htdocs\api\Core\Router.php(170): call_user_func_array(Array, Array)
#3 D:\XAMPP\htdocs\api\Core\Application.php(147): Core\Router->resolve()
#4 D:\XAMPP\htdocs\api\index.php(33): Core\Application::run()
#5 {main}
  thrown in D:\XAMPP\htdocs\api\Resources\Order\OrderModel.php on line 98
[17-Jul-2021 12:36:00 Europe/Berlin] PHP Fatal error:  Uncaught Error: Call to undefined function Resources\Auth\decipher() in D:\XAMPP\htdocs\api\Resources\Auth\AuthModel.php:70
Stack trace:
#0 D:\XAMPP\htdocs\api\Resources\Auth\AuthController.php(88): Resources\Auth\AuthModel->insertStaff(Array)
#1 [internal function]: Resources\Auth\AuthController->register()
#2 D:\XAMPP\htdocs\api\Core\Router.php(170): call_user_func_array(Array, Array)
#3 D:\XAMPP\htdocs\api\Core\Application.php(147): Core\Router->resolve()
#4 D:\XAMPP\htdocs\api\index.php(33): Core\Application::run()
#5 {main}
  thrown in D:\XAMPP\htdocs\api\Resources\Auth\AuthModel.php on line 70
[17-Jul-2021 12:36:50 Europe/Berlin] PHP Warning:  Undefined variable $keys in D:\XAMPP\htdocs\api\Resources\Auth\AuthModel.php on line 62
[17-Jul-2021 12:36:50 Europe/Berlin] PHP Fatal error:  Uncaught TypeError: array_search(): Argument #2 ($haystack) must be of type array, null given in D:\XAMPP\htdocs\api\Resources\Auth\AuthModel.php:62
Stack trace:
#0 D:\XAMPP\htdocs\api\Resources\Auth\AuthModel.php(62): array_search('C', NULL)
#1 D:\XAMPP\htdocs\api\Resources\Auth\AuthModel.php(70): Resources\Auth\AuthModel->decipher('kiupaC')
#2 D:\XAMPP\htdocs\api\Resources\Auth\AuthController.php(88): Resources\Auth\AuthModel->insertStaff(Array)
#3 [internal function]: Resources\Auth\AuthController->register()
#4 D:\XAMPP\htdocs\api\Core\Router.php(170): call_user_func_array(Array, Array)
#5 D:\XAMPP\htdocs\api\Core\Application.php(147): Core\Router->resolve()
#6 D:\XAMPP\htdocs\api\index.php(33): Core\Application::run()
#7 {main}
  thrown in D:\XAMPP\htdocs\api\Resources\Auth\AuthModel.php on line 62
[17-Jul-2021 12:37:20 Europe/Berlin] PHP Warning:  Trying to access array offset on value of type null in D:\XAMPP\htdocs\api\Core\Authorizer.php on line 85
[17-Jul-2021 12:37:20 Europe/Berlin] PHP Warning:  Trying to access array offset on value of type null in D:\XAMPP\htdocs\api\Core\Authorizer.php on line 86
[17-Jul-2021 12:37:20 Europe/Berlin] PHP Warning:  Trying to access array offset on value of type null in D:\XAMPP\htdocs\api\Core\Authorizer.php on line 87
[17-Jul-2021 12:38:29 Europe/Berlin] PHP Warning:  Trying to access array offset on value of type null in D:\XAMPP\htdocs\api\Core\Authorizer.php on line 85
[17-Jul-2021 12:38:29 Europe/Berlin] PHP Warning:  Trying to access array offset on value of type null in D:\XAMPP\htdocs\api\Core\Authorizer.php on line 86
[17-Jul-2021 12:38:29 Europe/Berlin] PHP Warning:  Trying to access array offset on value of type null in D:\XAMPP\htdocs\api\Core\Authorizer.php on line 87
[17-Jul-2021 12:55:23 Europe/Berlin] PHP Fatal error:  Uncaught PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'restaurant_id' in 'field list' in D:\XAMPP\htdocs\api\vendor\illuminate\database\Connection.php:465
Stack trace:
#0 D:\XAMPP\htdocs\api\vendor\illuminate\database\Connection.php(465): PDO->prepare('insert into `us...')
#1 D:\XAMPP\htdocs\api\vendor\illuminate\database\Connection.php(671): Illuminate\Database\Connection->Illuminate\Database\{closure}('insert into `us...', Array)
#2 D:\XAMPP\htdocs\api\vendor\illuminate\database\Connection.php(638): Illuminate\Database\Connection->runQueryCallback('insert into `us...', Array, Object(Closure))
#3 D:\XAMPP\htdocs\api\vendor\illuminate\database\Connection.php(472): Illuminate\Database\Connection->run('insert into `us...', Array, Object(Closure))
#4 D:\XAMPP\htdocs\api\vendor\illuminate\database\Connection.php(424): Illuminate\Database\Connection->statement('insert into `us...', Array)
#5 D:\XAMPP\htdocs\api\vendor\illuminate\database\Query\Processors\Processor.php(32): Illuminate\Database\Connection->insert('insert into `us...', Array)
#6 D:\XAMPP\htdocs\api\vendor\illuminate\database\Query\Builder.php(2882): Illuminate\Database\Query\Processors\Processor->processInsertGetId(Object(Illuminate\Database\Query\Builder), 'insert into `us...', Array, NULL)
#7 D:\XAMPP\htdocs\api\Resources\Auth\AuthModel.php(77): Illuminate\Database\Query\Builder->insertGetId(Array)
#8 D:\XAMPP\htdocs\api\Resources\Auth\AuthController.php(87): Resources\Auth\AuthModel->insertStaff(Array)
#9 [internal function]: Resources\Auth\AuthController->register()
#10 D:\XAMPP\htdocs\api\Core\Router.php(170): call_user_func_array(Array, Array)
#11 D:\XAMPP\htdocs\api\Core\Application.php(147): Core\Router->resolve()
#12 D:\XAMPP\htdocs\api\index.php(33): Core\Application::run()
#13 {main}

Next Illuminate\Database\QueryException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'restaurant_id' in 'field list' (SQL: insert into `users` (`role`, `first_name`, `last_name`, `date_of_birth`, `phone_number`, `password`, `email`, `gender`, `restaurant_id`, `confirmation_code`) values (staff, Mohamed, Ahmed Abdelnabey, 1999-11-11, 01110685449, $2y$10$Mpo7YVDivQgMkjn/CAB2TOOrhc9rmTxgrbc9F0phz1v7/9zuExp2K, TheMoo@aa.c, male, kiupaC, 22964)) in D:\XAMPP\htdocs\api\vendor\illuminate\database\Connection.php:678
Stack trace:
#0 D:\XAMPP\htdocs\api\vendor\illuminate\database\Connection.php(638): Illuminate\Database\Connection->runQueryCallback('insert into `us...', Array, Object(Closure))
#1 D:\XAMPP\htdocs\api\vendor\illuminate\database\Connection.php(472): Illuminate\Database\Connection->run('insert into `us...', Array, Object(Closure))
#2 D:\XAMPP\htdocs\api\vendor\illuminate\database\Connection.php(424): Illuminate\Database\Connection->statement('insert into `us...', Array)
#3 D:\XAMPP\htdocs\api\vendor\illuminate\database\Query\Processors\Processor.php(32): Illuminate\Database\Connection->insert('insert into `us...', Array)
#4 D:\XAMPP\htdocs\api\vendor\illuminate\database\Query\Builder.php(2882): Illuminate\Database\Query\Processors\Processor->processInsertGetId(Object(Illuminate\Database\Query\Builder), 'insert into `us...', Array, NULL)
#5 D:\XAMPP\htdocs\api\Resources\Auth\AuthModel.php(77): Illuminate\Database\Query\Builder->insertGetId(Array)
#6 D:\XAMPP\htdocs\api\Resources\Auth\AuthController.php(87): Resources\Auth\AuthModel->insertStaff(Array)
#7 [internal function]: Resources\Auth\AuthController->register()
#8 D:\XAMPP\htdocs\api\Core\Router.php(170): call_user_func_array(Array, Array)
#9 D:\XAMPP\htdocs\api\Core\Application.php(147): Core\Router->resolve()
#10 D:\XAMPP\htdocs\api\index.php(33): Core\Application::run()
#11 {main}
  thrown in D:\XAMPP\htdocs\api\vendor\illuminate\database\Connection.php on line 678
[17-Jul-2021 13:31:12 Europe/Berlin] PHP Fatal error:  Uncaught PDOException: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '0' for key 'PRIMARY' in D:\XAMPP\htdocs\api\vendor\illuminate\database\Connection.php:471
Stack trace:
#0 D:\XAMPP\htdocs\api\vendor\illuminate\database\Connection.php(471): PDOStatement->execute()
#1 D:\XAMPP\htdocs\api\vendor\illuminate\database\Connection.php(671): Illuminate\Database\Connection->Illuminate\Database\{closure}('insert into `st...', Array)
#2 D:\XAMPP\htdocs\api\vendor\illuminate\database\Connection.php(638): Illuminate\Database\Connection->runQueryCallback('insert into `st...', Array, Object(Closure))
#3 D:\XAMPP\htdocs\api\vendor\illuminate\database\Connection.php(472): Illuminate\Database\Connection->run('insert into `st...', Array, Object(Closure))
#4 D:\XAMPP\htdocs\api\vendor\illuminate\database\Connection.php(424): Illuminate\Database\Connection->statement('insert into `st...', Array)
#5 D:\XAMPP\htdocs\api\vendor\illuminate\database\Query\Builder.php(2838): Illuminate\Database\Connection->insert('insert into `st...', Array)
#6 D:\XAMPP\htdocs\api\Resources\Auth\AuthModel.php(90): Illuminate\Database\Query\Builder->insert(Array)
#7 D:\XAMPP\htdocs\api\Resources\Auth\AuthController.php(87): Resources\Auth\AuthModel->insertStaff(Array)
#8 [internal function]: Resources\Auth\AuthController->register()
#9 D:\XAMPP\htdocs\api\Core\Router.php(170): call_user_func_array(Array, Array)
#10 D:\XAMPP\htdocs\api\Core\Application.php(147): Core\Router->resolve()
#11 D:\XAMPP\htdocs\api\index.php(33): Core\Application::run()
#12 {main}

Next Illuminate\Database\QueryException: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '0' for key 'PRIMARY' (SQL: insert into `staff` (`user_id`, `restaurant_id`) values (129, 1)) in D:\XAMPP\htdocs\api\vendor\illuminate\database\Connection.php:678
Stack trace:
#0 D:\XAMPP\htdocs\api\vendor\illuminate\database\Connection.php(638): Illuminate\Database\Connection->runQueryCallback('insert into `st...', Array, Object(Closure))
#1 D:\XAMPP\htdocs\api\vendor\illuminate\database\Connection.php(472): Illuminate\Database\Connection->run('insert into `st...', Array, Object(Closure))
#2 D:\XAMPP\htdocs\api\vendor\illuminate\database\Connection.php(424): Illuminate\Database\Connection->statement('insert into `st...', Array)
#3 D:\XAMPP\htdocs\api\vendor\illuminate\database\Query\Builder.php(2838): Illuminate\Database\Connection->insert('insert into `st...', Array)
#4 D:\XAMPP\htdocs\api\Resources\Auth\AuthModel.php(90): Illuminate\Database\Query\Builder->insert(Array)
#5 D:\XAMPP\htdocs\api\Resources\Auth\AuthController.php(87): Resources\Auth\AuthModel->insertStaff(Array)
#6 [internal function]: Resources\Auth\AuthController->register()
#7 D:\XAMPP\htdocs\api\Core\Router.php(170): call_user_func_array(Array, Array)
#8 D:\XAMPP\htdocs\api\Core\Application.php(147): Core\Router->resolve()
#9 D:\XAMPP\htdocs\api\index.php(33): Core\Application::run()
#10 {main}
  thrown in D:\XAMPP\htdocs\api\vendor\illuminate\database\Connection.php on line 678
[17-Jul-2021 13:40:27 Europe/Berlin] PHP Fatal error:  Uncaught Error: Class "Resources\User\OrderModel" not found in D:\XAMPP\htdocs\api\Resources\User\UserController.php:35
Stack trace:
#0 [internal function]: Resources\User\UserController->insertPreference()
#1 D:\XAMPP\htdocs\api\Core\Router.php(170): call_user_func_array(Array, Array)
#2 D:\XAMPP\htdocs\api\Core\Application.php(147): Core\Router->resolve()
#3 D:\XAMPP\htdocs\api\index.php(33): Core\Application::run()
#4 {main}
  thrown in D:\XAMPP\htdocs\api\Resources\User\UserController.php on line 35
[21-Jul-2021 22:15:50 Europe/Berlin] PHP Warning:  Undefined property: stdClass::$data in D:\XAMPP\htdocs\api\Resources\Menu\MenuController.php on line 13
[21-Jul-2021 22:16:33 Europe/Berlin] PHP Warning:  Attempt to read property "data" on string in D:\XAMPP\htdocs\api\Resources\Menu\MenuController.php on line 13
[21-Jul-2021 22:18:35 Europe/Berlin] PHP Warning:  file_get_contents(http://127.0.0.1:5000/menu/recommendations/1/4): Failed to open stream: No connection could be made because the target machine actively refused it in D:\XAMPP\htdocs\api\Resources\Menu\MenuController.php on line 12
[21-Jul-2021 22:22:01 Europe/Berlin] PHP Warning:  file_get_contents(http://127.0.0.1:5000/menu/recommendations/1/4): Failed to open stream: HTTP request failed! HTTP/1.0 500 INTERNAL SERVER ERROR
 in D:\XAMPP\htdocs\api\Resources\Menu\MenuController.php on line 12
[22-Jul-2021 00:14:01 Europe/Berlin] PHP Warning:  Attempt to read property "Data" on null in D:\XAMPP\htdocs\api\Resources\Restaurant\RestaurantController.php on line 102
[22-Jul-2021 00:16:40 Europe/Berlin] PHP Warning:  file_get_contents(http://127.0.0.1:5000/restaurant/branch/recommendation/1): Failed to open stream: No connection could be made because the target machine actively refused it in D:\XAMPP\htdocs\api\Resources\Restaurant\RestaurantController.php on line 101
[22-Jul-2021 00:18:53 Europe/Berlin] PHP Warning:  Undefined property: stdClass::$data in D:\XAMPP\htdocs\api\Resources\Restaurant\RestaurantController.php on line 102
[22-Jul-2021 00:25:10 Europe/Berlin] PHP Fatal error:  Uncaught PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'users.name' in 'field list' in D:\XAMPP\htdocs\api\vendor\illuminate\database\Connection.php:338
Stack trace:
#0 D:\XAMPP\htdocs\api\vendor\illuminate\database\Connection.php(338): PDO->prepare('select `orders`...')
#1 D:\XAMPP\htdocs\api\vendor\illuminate\database\Connection.php(671): Illuminate\Database\Connection->Illuminate\Database\{closure}('select `orders`...', Array)
#2 D:\XAMPP\htdocs\api\vendor\illuminate\database\Connection.php(638): Illuminate\Database\Connection->runQueryCallback('select `orders`...', Array, Object(Closure))
#3 D:\XAMPP\htdocs\api\vendor\illuminate\database\Connection.php(346): Illuminate\Database\Connection->run('select `orders`...', Array, Object(Closure))
#4 D:\XAMPP\htdocs\api\vendor\illuminate\database\Query\Builder.php(2313): Illuminate\Database\Connection->select('select `orders`...', Array, true)
#5 D:\XAMPP\htdocs\api\vendor\illuminate\database\Query\Builder.php(2301): Illuminate\Database\Query\Builder->runSelect()
#6 D:\XAMPP\htdocs\api\vendor\illuminate\database\Query\Builder.php(2796): Illuminate\Database\Query\Builder->Illuminate\Database\Query\{closure}()
#7 D:\XAMPP\htdocs\api\vendor\illuminate\database\Query\Builder.php(2302): Illuminate\Database\Query\Builder->onceWithColumns(Array, Object(Closure))
#8 D:\XAMPP\htdocs\api\Resources\Order\OrderModel.php(71): Illuminate\Database\Query\Builder->get()
#9 D:\XAMPP\htdocs\api\Resources\Order\OrderController.php(156): Resources\Order\OrderModel->getNonFinished('orders.restaura...', '1')
#10 [internal function]: Resources\Order\OrderController->getRestaurantNonFinishedOrders('1')
#11 D:\XAMPP\htdocs\api\Core\Router.php(170): call_user_func_array(Array, Array)
#12 D:\XAMPP\htdocs\api\Core\Application.php(155): Core\Router->resolve()
#13 D:\XAMPP\htdocs\api\index.php(33): Core\Application::run()
#14 {main}

Next Illuminate\Database\QueryException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'users.name' in 'field list' (SQL: select `orders`.*, `items`.`name` as `item_name`, `order_details`.`quantity` as `qty`, `order_details`.`total` as `total`, `users`.`name` from `orders` inner join `order_details` on `orders`.`id` = `order_details`.`order_id` inner join `items` on `order_details`.`meal_id` = `items`.`id` inner join `customers` on `orders`.`customer_id` = `customers`.`id` inner join `users` on `users`.`id` = `customers`.`user_id` where `orders`.`is_finished` = 0 and `orders`.`is_deleted` = 0 and `orders`.`restaurant_id` = 1) in D:\XAMPP\htdocs\api\vendor\illuminate\database\Connection.php:678
Stack trace:
#0 D:\XAMPP\htdocs\api\vendor\illuminate\database\Connection.php(638): Illuminate\Database\Connection->runQueryCallback('select `orders`...', Array, Object(Closure))
#1 D:\XAMPP\htdocs\api\vendor\illuminate\database\Connection.php(346): Illuminate\Database\Connection->run('select `orders`...', Array, Object(Closure))
#2 D:\XAMPP\htdocs\api\vendor\illuminate\database\Query\Builder.php(2313): Illuminate\Database\Connection->select('select `orders`...', Array, true)
#3 D:\XAMPP\htdocs\api\vendor\illuminate\database\Query\Builder.php(2301): Illuminate\Database\Query\Builder->runSelect()
#4 D:\XAMPP\htdocs\api\vendor\illuminate\database\Query\Builder.php(2796): Illuminate\Database\Query\Builder->Illuminate\Database\Query\{closure}()
#5 D:\XAMPP\htdocs\api\vendor\illuminate\database\Query\Builder.php(2302): Illuminate\Database\Query\Builder->onceWithColumns(Array, Object(Closure))
#6 D:\XAMPP\htdocs\api\Resources\Order\OrderModel.php(71): Illuminate\Database\Query\Builder->get()
#7 D:\XAMPP\htdocs\api\Resources\Order\OrderController.php(156): Resources\Order\OrderModel->getNonFinished('orders.restaura...', '1')
#8 [internal function]: Resources\Order\OrderController->getRestaurantNonFinishedOrders('1')
#9 D:\XAMPP\htdocs\api\Core\Router.php(170): call_user_func_array(Array, Array)
#10 D:\XAMPP\htdocs\api\Core\Application.php(155): Core\Router->resolve()
#11 D:\XAMPP\htdocs\api\index.php(33): Core\Application::run()
#12 {main}
  thrown in D:\XAMPP\htdocs\api\vendor\illuminate\database\Connection.php on line 678
[22-Jul-2021 00:27:06 Europe/Berlin] PHP Fatal error:  Uncaught PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'users.name' in 'field list' in D:\XAMPP\htdocs\api\vendor\illuminate\database\Connection.php:338
Stack trace:
#0 D:\XAMPP\htdocs\api\vendor\illuminate\database\Connection.php(338): PDO->prepare('select `orders`...')
#1 D:\XAMPP\htdocs\api\vendor\illuminate\database\Connection.php(671): Illuminate\Database\Connection->Illuminate\Database\{closure}('select `orders`...', Array)
#2 D:\XAMPP\htdocs\api\vendor\illuminate\database\Connection.php(638): Illuminate\Database\Connection->runQueryCallback('select `orders`...', Array, Object(Closure))
#3 D:\XAMPP\htdocs\api\vendor\illuminate\database\Connection.php(346): Illuminate\Database\Connection->run('select `orders`...', Array, Object(Closure))
#4 D:\XAMPP\htdocs\api\vendor\illuminate\database\Query\Builder.php(2313): Illuminate\Database\Connection->select('select `orders`...', Array, true)
#5 D:\XAMPP\htdocs\api\vendor\illuminate\database\Query\Builder.php(2301): Illuminate\Database\Query\Builder->runSelect()
#6 D:\XAMPP\htdocs\api\vendor\illuminate\database\Query\Builder.php(2796): Illuminate\Database\Query\Builder->Illuminate\Database\Query\{closure}()
#7 D:\XAMPP\htdocs\api\vendor\illuminate\database\Query\Builder.php(2302): Illuminate\Database\Query\Builder->onceWithColumns(Array, Object(Closure))
#8 D:\XAMPP\htdocs\api\Resources\Order\OrderModel.php(71): Illuminate\Database\Query\Builder->get()
#9 D:\XAMPP\htdocs\api\Resources\Order\OrderController.php(156): Resources\Order\OrderModel->getNonFinished('orders.restaura...', '1')
#10 [internal function]: Resources\Order\OrderController->getRestaurantNonFinishedOrders('1')
#11 D:\XAMPP\htdocs\api\Core\Router.php(170): call_user_func_array(Array, Array)
#12 D:\XAMPP\htdocs\api\Core\Application.php(155): Core\Router->resolve()
#13 D:\XAMPP\htdocs\api\index.php(33): Core\Application::run()
#14 {main}

Next Illuminate\Database\QueryException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'users.name' in 'field list' (SQL: select `orders`.*, `items`.`name` as `item_name`, `order_details`.`quantity` as `qty`, `order_details`.`total` as `total`, `users`.`name` as `customer_name` from `orders` inner join `order_details` on `orders`.`id` = `order_details`.`order_id` inner join `items` on `order_details`.`meal_id` = `items`.`id` inner join `customers` on `orders`.`customer_id` = `customers`.`id` inner join `users` on `users`.`id` = `customers`.`user_id` where `orders`.`is_finished` = 0 and `orders`.`is_deleted` = 0 and `orders`.`restaurant_id` = 1) in D:\XAMPP\htdocs\api\vendor\illuminate\database\Connection.php:678
Stack trace:
#0 D:\XAMPP\htdocs\api\vendor\illuminate\database\Connection.php(638): Illuminate\Database\Connection->runQueryCallback('select `orders`...', Array, Object(Closure))
#1 D:\XAMPP\htdocs\api\vendor\illuminate\database\Connection.php(346): Illuminate\Database\Connection->run('select `orders`...', Array, Object(Closure))
#2 D:\XAMPP\htdocs\api\vendor\illuminate\database\Query\Builder.php(2313): Illuminate\Database\Connection->select('select `orders`...', Array, true)
#3 D:\XAMPP\htdocs\api\vendor\illuminate\database\Query\Builder.php(2301): Illuminate\Database\Query\Builder->runSelect()
#4 D:\XAMPP\htdocs\api\vendor\illuminate\database\Query\Builder.php(2796): Illuminate\Database\Query\Builder->Illuminate\Database\Query\{closure}()
#5 D:\XAMPP\htdocs\api\vendor\illuminate\database\Query\Builder.php(2302): Illuminate\Database\Query\Builder->onceWithColumns(Array, Object(Closure))
#6 D:\XAMPP\htdocs\api\Resources\Order\OrderModel.php(71): Illuminate\Database\Query\Builder->get()
#7 D:\XAMPP\htdocs\api\Resources\Order\OrderController.php(156): Resources\Order\OrderModel->getNonFinished('orders.restaura...', '1')
#8 [internal function]: Resources\Order\OrderController->getRestaurantNonFinishedOrders('1')
#9 D:\XAMPP\htdocs\api\Core\Router.php(170): call_user_func_array(Array, Array)
#10 D:\XAMPP\htdocs\api\Core\Application.php(155): Core\Router->resolve()
#11 D:\XAMPP\htdocs\api\index.php(33): Core\Application::run()
#12 {main}
  thrown in D:\XAMPP\htdocs\api\vendor\illuminate\database\Connection.php on line 678
[22-Jul-2021 00:29:44 Europe/Berlin] PHP Fatal error:  Uncaught PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'users.name' in 'field list' in D:\XAMPP\htdocs\api\vendor\illuminate\database\Connection.php:338
Stack trace:
#0 D:\XAMPP\htdocs\api\vendor\illuminate\database\Connection.php(338): PDO->prepare('select `orders`...')
#1 D:\XAMPP\htdocs\api\vendor\illuminate\database\Connection.php(671): Illuminate\Database\Connection->Illuminate\Database\{closure}('select `orders`...', Array)
#2 D:\XAMPP\htdocs\api\vendor\illuminate\database\Connection.php(638): Illuminate\Database\Connection->runQueryCallback('select `orders`...', Array, Object(Closure))
#3 D:\XAMPP\htdocs\api\vendor\illuminate\database\Connection.php(346): Illuminate\Database\Connection->run('select `orders`...', Array, Object(Closure))
#4 D:\XAMPP\htdocs\api\vendor\illuminate\database\Query\Builder.php(2313): Illuminate\Database\Connection->select('select `orders`...', Array, true)
#5 D:\XAMPP\htdocs\api\vendor\illuminate\database\Query\Builder.php(2301): Illuminate\Database\Query\Builder->runSelect()
#6 D:\XAMPP\htdocs\api\vendor\illuminate\database\Query\Builder.php(2796): Illuminate\Database\Query\Builder->Illuminate\Database\Query\{closure}()
#7 D:\XAMPP\htdocs\api\vendor\illuminate\database\Query\Builder.php(2302): Illuminate\Database\Query\Builder->onceWithColumns(Array, Object(Closure))
#8 D:\XAMPP\htdocs\api\Resources\Order\OrderModel.php(72): Illuminate\Database\Query\Builder->get()
#9 D:\XAMPP\htdocs\api\Resources\Order\OrderController.php(156): Resources\Order\OrderModel->getNonFinished('orders.restaura...', '1')
#10 [internal function]: Resources\Order\OrderController->getRestaurantNonFinishedOrders('1')
#11 D:\XAMPP\htdocs\api\Core\Router.php(170): call_user_func_array(Array, Array)
#12 D:\XAMPP\htdocs\api\Core\Application.php(155): Core\Router->resolve()
#13 D:\XAMPP\htdocs\api\index.php(33): Core\Application::run()
#14 {main}

Next Illuminate\Database\QueryException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'users.name' in 'field list' (SQL: select `orders`.*, `items`.`name` as `item_name`, `order_details`.`quantity` as `qty`, `order_details`.`total` as `total`, `users`.`name` as `customer_name` from `orders` inner join `customers` on `orders`.`customer_id` = `customers`.`id` inner join `users` on `users`.`id` = `customers`.`user_id` inner join `order_details` on `orders`.`id` = `order_details`.`order_id` inner join `items` on `order_details`.`meal_id` = `items`.`id` where `orders`.`is_finished` = 0 and `orders`.`is_deleted` = 0 and `orders`.`restaurant_id` = 1) in D:\XAMPP\htdocs\api\vendor\illuminate\database\Connection.php:678
Stack trace:
#0 D:\XAMPP\htdocs\api\vendor\illuminate\database\Connection.php(638): Illuminate\Database\Connection->runQueryCallback('select `orders`...', Array, Object(Closure))
#1 D:\XAMPP\htdocs\api\vendor\illuminate\database\Connection.php(346): Illuminate\Database\Connection->run('select `orders`...', Array, Object(Closure))
#2 D:\XAMPP\htdocs\api\vendor\illuminate\database\Query\Builder.php(2313): Illuminate\Database\Connection->select('select `orders`...', Array, true)
#3 D:\XAMPP\htdocs\api\vendor\illuminate\database\Query\Builder.php(2301): Illuminate\Database\Query\Builder->runSelect()
#4 D:\XAMPP\htdocs\api\vendor\illuminate\database\Query\Builder.php(2796): Illuminate\Database\Query\Builder->Illuminate\Database\Query\{closure}()
#5 D:\XAMPP\htdocs\api\vendor\illuminate\database\Query\Builder.php(2302): Illuminate\Database\Query\Builder->onceWithColumns(Array, Object(Closure))
#6 D:\XAMPP\htdocs\api\Resources\Order\OrderModel.php(72): Illuminate\Database\Query\Builder->get()
#7 D:\XAMPP\htdocs\api\Resources\Order\OrderController.php(156): Resources\Order\OrderModel->getNonFinished('orders.restaura...', '1')
#8 [internal function]: Resources\Order\OrderController->getRestaurantNonFinishedOrders('1')
#9 D:\XAMPP\htdocs\api\Core\Router.php(170): call_user_func_array(Array, Array)
#10 D:\XAMPP\htdocs\api\Core\Application.php(155): Core\Router->resolve()
#11 D:\XAMPP\htdocs\api\index.php(33): Core\Application::run()
#12 {main}
  thrown in D:\XAMPP\htdocs\api\vendor\illuminate\database\Connection.php on line 678
